### ISSUE TITLE
Trailing space within quotes

### ISSUE THREAD

**Issue by EricEdwardBryant** [wadetb/Sublime-Text-Advanced-CSV#18]
Love the package; helps me avoid Excel! Though I have one concern.

When justifying the following CSV:

```
a,b
"text,with,comma",blah
looooooooooooooooooong text,blah
```

I get:

```
a                          ,b   
"text,with,comma"          ,blah
looooooooooooooooooong text,blah
```

Then when I compact, the trailing space is added within the quotes:

```
a,b
"text,with,comma          ",blah
looooooooooooooooooong text,blah
```

Thus my CSV has been mildly corrupted.

**Comment by wadetb** [comment]
Thanks for the comments and the report!  We definitely shouldn't be altering anything inside quotes, I'll fix it.

**Comment by wadetb** [comment]
Fixed, sorry it took such a long time.
