### ISSUE TITLE
Listed Key Bindings do not work on Mac

### ISSUE THREAD

**Issue by jess-fortier** [wadetb/Sublime-Text-Advanced-CSV#23]
Neither ctrl nor cmd (in place of ctrl) works for the given key bindings on Mac.

**Comment by wadetb** [comment]
Hi, thanks for the report. It seems to be working alright on my iMac using Ctrl+,

This is how I am pressing the keys:

Press Ctrl
Press Comma
Release Comma
Release Ctrl

Press Down Arrow (to sort)
Release Down Arrow

**Comment by wadetb** [comment]
Closed out old issue, let me know if its still a problem.

**Comment by echennh** [comment]
This is still a problem - I press and hold ctrl, comma, and space, and the columns don't justify - same with if I use cmd instead of ctrl.
