### ISSUE TITLE
How to use Sort by column

### ISSUE THREAD

**Issue by micyew** [wadetb/Sublime-Text-Advanced-CSV#25]
Hi,

Can I know how do I use the "Sort by column"? I've a five columns csv and I would like to sort using the 3 column, how do I do that?

Thanks..

**Comment by wadetb** [comment]
Hi, just click inside the column and then use Ctrl+comma and then hit the up or down arrow.

**Comment by micyew** [comment]
Wow... This is magic... Didnt know that it is so simple....thanks..
