### ISSUE TITLE
Cannot specify tab as delimiter

### ISSUE THREAD

**Issue by baryonyx5** [wadetb/Sublime-Text-Advanced-CSV#26]
Unless, I'm using the incorrect syntax, it doesn't appear possible to set tab (\t) as a delimiter.  

I receive "'\t' is not a valid delimiter, reverting to ','." when attempting to do so from the settings file or using the command.  

If it is currently not possible, could you consider adding the option?  Tab is a fairly common delimiter.  

Otherwise, great plugin. 

Thanks

**Comment by danmichaelo** [comment]
You need to actually type a tab, not \t

**Comment by wadetb** [comment]
\t is explicitly supported in the latest version, and you can also name your file .tsv for automatic detection.
