### ISSUE TITLE
Default delimiter

### ISSUE THREAD

**Issue by lorenzofanchi** [wadetb/Sublime-Text-Advanced-CSV#27]
Hi,

Great package! I would love to be able to set the default delimiter, as I mostly work with TSV files. Now it's a bit of a hassle to have to change the delimiter every time..

Alternatively, auto-detection of the delimiter would be even better :)

Thanks!

**Comment by dacook** [comment]
@lorenzofanchi you should be able to set the default delimiter in your user preferences (AdvancedCSV.sublime-settings).

But I also would love to see auto detection based on filename. A user-defineable would give us enough flexibility, eg:

```
"delimiter_mapping": {
    "*.tsv": "\t",
    "*.psv": "|"
  }
```
(if no filename match, it would use the default delimiter)

**Comment by wadetb** [comment]
Added mapping as described.

**Comment by dacook** [comment]
Thanks Wade!
