### ISSUE TITLE
Naming of shortcuts in menus

### ISSUE THREAD

**Issue by bmralph** [wadetb/Sublime-Text-Advanced-CSV#28]
Hi there. Windows user.

When using Tools>CSV> to Justify columns, Compact columns etc. the shortcuts listed next to the menu selection is displayed as e.g. "Ctrl+,, "

This is really confusing as one comma is an input, one comma is a break in input and spaces are not shown.

Would be more understandable to display "Ctrl+comma, space"

:)

**Comment by wadetb** [comment]
Unfortunately this is a behavior of Sublime Text. 

Even when I write Ctrl+comma in the bindings file, the UI displays "Ctrl+,"
