### ISSUE TITLE
Extension options not available

### ISSUE THREAD

**Issue by nikonikolov** [wadetb/Sublime-Text-Advanced-CSV#31]
I successfully installed the extension, can select that I want to use it for syntax highlight and everything works fine. However, when I right-click or go to Tools->CSV, all options appear in grey and are not available to select. How should I fix that? I am using Sublime Text 3 Build 3114 on Linux.

**Comment by wadetb** [comment]
Hi Nikolay, thanks for the report.


Is there any error message in the ST3 output window?


I don't currently have a Linux PC to test with but will try to set one up.


Get Outlook for Android






On Tue, Aug 2, 2016 at 11:36 AM -0400, "Nikolay Nikolov" <notifications@github.com> wrote:












I successfully installed the extension, can select that I want to use it for syntax highlight and everything works fine. However, when I right-click or go to Tools->CSV, all options appear in grey and are not available to select. How should I fix that? I am using Sublime Text 3 Build 3114 on Linux.

**Comment by nikonikolov** [comment]
It's fixed now. Sorry it was my mistake, I manually installed the package by placing it in the Packages directory but did not notice that the .sublime-package archive contained a folder with the files rather than the files themselves. Sorry about the false issue!
