### ISSUE TITLE
Sort breaks when repeating it several times

### ISSUE THREAD

**Issue by jheeffer** [wadetb/Sublime-Text-Advanced-CSV#33]
Hi!

I use Sublime Text 2.0.2 on Windows 10. I just installed Text-Advanced-CSV, great tool, no bullshit csv editing!

However I had this file open:

https://raw.githubusercontent.com/open-numbers/ddf--gapminder--systema_globalis/ed96f42cde3ad59a7a99eed97ae898c34f240ab2/ddf--entities--geo--country.csv

I was playing around a bit and wanted to sort it. My sort turned out in a random order instead of sorted.

I tested a bit and:

- When freshly opening the file, you have to sort up and down a bit before the bug shows up, sometimes repeat the same sort order twice
- Erroneous seemingly "Random" sort order is the same every time

![image](https://cloud.githubusercontent.com/assets/1596071/20029740/01e087f6-a355-11e6-999f-420b8ba6df31.png)

**Comment by wadetb** [comment]
Thanks for the report! I was able to reproduce unexpected sorting behavior with the file you uploaded. 

My theory is that after the sort, the cursor is *sometimes* moved to another column, and so the subsequent sort is based upon different data.

When testing, I find that the random sorting behavior does not occur if I click the mouse on the first column after each sort command. Is this the case for you as well?

**Comment by wadetb** [comment]
Fixed in latest release.
