### ISSUE TITLE
The dependency "numpy" is either not available on this platform or for this version of Sublime Text

### ISSUE THREAD

**Issue by evandrocoan** [wadetb/Sublime-Text-Advanced-CSV#39]
### The dependency "numpy" is either not available on this platform or for this version of Sublime Text

The problem about this is, the message box popping every time you restart Sublime Text:

![image](https://cloud.githubusercontent.com/assets/5332158/20645115/e13541b8-b439-11e6-8205-562d81d31d05.png)

Every time you open Sublime Text, this is showed on the console:
```
Package Control: Using cached content for https://api.github.com/repos/math2001/FileManager/commits?sha=master&per_page=1 from D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Packages\User\Package Control.cache\1baed789e70a709c4915efe4ace1fb8f
Package Control: The dependency "numpy" is either not available on this platform or for this version of Sublime Text
Package Control: Installed missing dependency numpy
Package Control: Skipping automatic upgrade, last run at 2016-11-26 23:31:46, next run at 2016-11-27 00:31:46 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

And the message box just above keeps popping up.

### Expected behavior

If some package is unavailable, do not keep up popping a notice box every time you open Sublime Text, saying the dependency was installed, while actually the dependency is not installed, neither available.

### How to reproduce the Issue

1. To install the package https://packagecontrol.io/packages/Advanced%20CSV
1. Restart you Sublime Text.

____

## "debug": true,

[full_log.txt](https://github.com/wbond/package_control/files/614713/full_log.txt)
Sublime Text Build 3126
Windows 10
Package Control Version 3.2.1

Originally reported on: 

1. https://github.com/wbond/package_control/issues/1197

**Comment by wadetb** [comment]
Hi @evandrocoan. Looks like the ST3 repository for numpy at https://github.com/komsit37/sublime-numpy/issues does not provide a Win32 version. Switching to the x64 version of Sublime Text should resolve the issue. I'll leave this ticket open to see if I can make fail gracefully, since the dependency is optional.

**Comment by evandrocoan** [comment]
Hi, @wadetb I think the big problem is on package control, which should know when stop trying to install dependencies not existents. But hey, :( there is not x32 dependencies? My system is x64, just Sublime Text is x32.

**Comment by wadetb** [comment]
I agree that it is a package control issue. 
One option would be to release a no-NumPy version of this extension, falling back to tinynumpy.
But that seems too heavy-handed.
Did you succeed in installing the x64 version of ST3?

**Comment by evandrocoan** [comment]
I do not tried, I removed the package, for now I am not using.

This package can just check whether the Sublime Text version is x86 then do not registry the dependency for Numpy?

**Comment by FichteFoll** [comment]
Packages can specify to only install dependencis on certain platforms.

It's not mentioned [in the example file](https://github.com/wbond/package_control/blob/master/example-dependencies.json) but is performed [in the source](https://github.com/wbond/package_control/blob/2bcface6c34544eb5b0258984f2803b7a3c98ffc/package_control/package_manager.py#L378).

**Comment by wadetb** [comment]
Excellent, thank you @FichteFoll.

**Comment by wadetb** [comment]
4786d037a761bc45e516f6b0624a839919ec6d05
