### ISSUE TITLE
Syntax error in config file just after installing

### ISSUE THREAD

**Issue by jlcanovas** [wadetb/Sublime-Text-Advanced-CSV#41]
Hi, 

I've just installed AdvancedCSV (v1.1.8) in my Sublime Text 2 (v2.0.2) using the Package Control (v3.2.1). Just after installing, an error is raised regarding line 6 col 3 of `AdvancedCSV.sublime-settings` file. This is the file:

```
{
  "delimiter_mapping": {
  	"*.csv": ",",
  	"*.psv": "|",
  	"*.tsv": "\t",
  },
  "delimiter": ",",
  "auto_quote": true
}
```

There is a trailing comma there, just before closing the bracket. Once installed, you can work with Sublime Text 2, but if you close the application, it won't start again as it will report this syntax problem.

I've fixed the issue in the file (removing the comma) and Sublime Text 2 starts normally. However, the Package Control then complains each time you start the application and reports this:

![issue](https://cloud.githubusercontent.com/assets/1996760/21174639/a70de2e4-c1de-11e6-8f3e-3c673274a195.PNG)

Even so, the plugin (and Sublime Text) seems to work fine, but all this looks quite burdensome.

**Comment by ccantarero72** [comment]
I have the same problem, and I solved it doing the same as @jlcanovas

**Comment by wadetb** [comment]
Hi guys, thanks for the report. I'm not sure how I missed this issue until now. I've mostly been testing with Sublime Text 3, but will review Sublime Text 2 support.

**Comment by jlcanovas** [comment]
Hi @wadetb, any update on this? Thks!

**Comment by wadetb** [comment]
Thanks for the reminder, I just installed ST2 and am looking at this now.

**Comment by wadetb** [comment]
I just released 1.0.9. The comma issue had been fixed, but I forgot to release a new version, my apologies.

On to the dependency issue. I was able to replicate the behavior but I'm not sure how to resolve it, it seems like a package control issue.

Here is the output from package control at the time of the dialog:

```
Package Control: Installing 1 missing dependency
Package Control: The dependency "numpy" is either not available on this platform or for this version of Sublime Text
Package Control: Installed missing dependency numpy
Package Control: Skipping automatic upgrade, last run at 2017-04-27 12:50:29, next run at 2017-04-27 13:50:29 or after
error: Package Control

1 missing dependency was just installed. Sublime Text should be restarted, otherwise one or more of the installed packages may not function properly.
```

From the output it appears to fail to install the dependency ("not available on this platform or for this version of Sublime Text") but then perhaps some higher level code fails to detect this error ("Installed missing dependency numpy").

**Comment by wadetb** [comment]
I confirmed that as a workaround, you can simply delete `dependencies.json` from `%APPDATA%\Sublime Text 2\Packages\Advanced CSV`.

**Comment by jlcanovas** [comment]
After installing the package again, the problem regarind the missing dependency was still there (as expected). I followed your indications (i.e., removing the file) and everything seems to work fine now. Thanks!
