### ISSUE TITLE
Embed NumPy package

### ISSUE THREAD

**Issue by wadetb** [wadetb/Sublime-Text-Advanced-CSV#5]
It's really hard to install the NumPy packages on some systems, and makes getting started with expressions quite difficult.

Figure out how to embed NumPy, including its platform specific shared objects, into the package for each platform.

**Comment by aziz** [comment]
`numpy` is now available on package control and you can set it as a dependency. 

https://packagecontrol.io/docs/dependencies
https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json#L237
