### ISSUE TITLE
Disable CSV commands when syntax is not CSV

### ISSUE THREAD

**Issue by aziz** [wadetb/Sublime-Text-Advanced-CSV#9]
Try to implement `is_enabled(<args>)` and `is_visible(<args>)` is your commands

**Comment by wadetb** [comment]
Thanks for the suggestion, I'll look into implementing these.

**Comment by wadetb** [comment]
Thinking about this some more, I'd like to extend the ability of the plugin to operate on tables in non-CSV files.  For example I'd like to be able to use the expression evaluation and column lineup features in tables or CSV data embedded in Markdown files.

**Comment by wadetb** [comment]
So if I wrote these callbacks they would have to do some heuristic matching, like "is there more than one column parseable from the text the cursor is in", as opposed to just "is this a .csv file".

**Comment by aziz** [comment]
I understand. It kinda make sense to me a well. I'm gonna close this issue.

**Comment by wadetb** [comment]
Thanks!  I'll revisit if I develop this heuristic ability further in the future.

**Comment by nicksspirit** [comment]
Have you been able to figure out the heuristic?

I think think that the best thing to do is to only enable the commands when the file is either csv or markdown. This way, we won't clutter the sub menu with commands that don't make sense in a specific context.
